<!DOCTYPE html>
<html>
    <head>
        <title></title>
        <?php require("view/include/meta.phtml"); ?>     
    </head>
    <body>
        <div id="header"></div>              
        <div id="topbar"></div>        
        <div id="wrapper">   
            <div id="smallbar"></div> 
            <div id="content">    
                <!-- ------------------------------------ -->
                <!-- ------------------------------------ -->
                <!-- BEGIN: Nội dung chính của trang web  -->
                <div id="primary">                    
                    <?php require($VIEW); ?>
                </div>
                <!-- END: Nội dung chính của trang web  -->
                <!-- ------------------------------------ -->
                <!-- ------------------------------------ -->
                <div id="secondary">
                    <?php require("view/include/secondary.phtml"); ?>                    
                </div>
            </div>            
            <div id="footer"></div>
        </div>         
    </body>
</html>
