<!DOCTYPE html>
<html lang="en">
<head>
    <title>Resume</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
<!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="./css/style.css">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
</head>
<body>
    <div class="col-md-offset-2 col-md-8" style="background: rgb(245, 242, 242)" id="wrapper">
    <div id="header">
        <div>
            <h2 id="name"> MAI KHANH HUYEN</h2>
            <p id="underline"></p>
            <h4 id="job">Developer </h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <h4 id="exp">LEARNING EXPERIENCE</h4>
            <div id="exprience">
                <div  id="exp1">
                <div>
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-record-fill" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M8 13A5 5 0 1 0 8 3a5 5 0 0 0 0 10z"/>
                      </svg>
                </div>
                <div>
                    <span id="forntbold">
                    DATABASE PROJECT 
                      </span>
                      <p>- Conducted by a group of 3-4 students <br>
                        - C#/ SQL</p>
                </div>
                <div>
                   <p>- Analyze, synthesize and practice teamwork skills in group relational database design activities. <br>
                     - Relational database design stages such as: data model, functional dependency, normal form, ...<br>
                    
                     - Apply techniques to define user requirements
                    
                    </p>
                </div>
            </div>
        </div>


        <div id="exprience">
            <div  id="exp1">
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-record-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 13A5 5 0 1 0 8 3a5 5 0 0 0 0 10z"/>
                  </svg>
            </div>
            <div>
                <span id="forntbold">
                SAFETY AND SECURITY IN INFORMATION SYSTEM                  </span>
                  <p>- Conducted by a group of 3-4 students <br>
                    - C#/SQL</p>
            </div>
            <div>
               <p>-	Use Oracle security mechanisms to implement security mechanisms for Hospital Information Management application
                
                </p>
            </div>
        </div>
    </div>


    <div id="exprience">
        <div  id="exp1">
        <div>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-record-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M8 13A5 5 0 1 0 8 3a5 5 0 0 0 0 10z"/>
              </svg>
        </div>
        <div>
            <span id="forntbold">
            INFORMATION SYSTEM FOR BUSINESS INTELLIGENCE   
              </span>
              <p>- Conducted by a group of 3-4 students <br>
                - PowerBI/ SSIS/ SSAS</p>
        </div>
        <div>
           <p>- Analysis of crash data in UK over 3-4 years. <br>
             - Design schema NDS, DDS <br>
             - Datawarehouse, ETL, OLAP <br>
            </p>
        </div>
    </div>
</div>

    </div>
</div>



<div class="row">
    <div class="col-md-12">
        <h4 id="exp">EDUCATION</h4>
        <div id="exprience">
            <div  id="edu">
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-record-fill" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M8 13A5 5 0 1 0 8 3a5 5 0 0 0 0 10z"/>
                  </svg>
            </div>
            <div>
                <span id="forntbold">
                    2018 - CURRENT 
                  </span>
                  <h6>University of Science - Vietnam National University Ho Chi Minh City</h6>
                  <p id="forntitalic"> 
                  Department of Information Systems - Faculty of Information Technology <br>
                  Cumulative GPA 7.8
                    </p>
            </div>
            
        </div>
    </div>

    <div class="row">
        <div class="col-md-5">
            <h4 id="contacts"> CONTACTS</h4>
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-fill" viewBox="0 0 16 16">
                    <path d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                  </svg>
                  <span id="space"> Female</span>
            </div>
            <br>
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar2-week-fill" viewBox="0 0 16 16">
                    <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zm9.954 3H2.545c-.3 0-.545.224-.545.5v1c0 .276.244.5.545.5h10.91c.3 0 .545-.224.545-.5v-1c0-.276-.244-.5-.546-.5zM8.5 7a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zm3 0a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1zM3 10.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5zm3.5-.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5h-1z"/>
                  </svg>
                  <span id="space"> 10/02/2000</span>
            </div>
            <br>
            <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                    <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
                  </svg> 
                  <span id="space"> District 7, Ho Chi Minh City</span>
            </div>
            <div>
            <br>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="M1.885.511a1.745 1.745 0 0 1 2.61.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"/>
              </svg> 
              <span id="space"> <a href="#">0348 666 044</a></span>
            </div>
            <br>
              <div>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope-fill" viewBox="0 0 16 16">
                    <path d="M.05 3.555A2 2 0 0 1 2 2h12a2 2 0 0 1 1.95 1.555L8 8.414.05 3.555ZM0 4.697v7.104l5.803-3.558L0 4.697ZM6.761 8.83l-6.57 4.027A2 2 0 0 0 2 14h12a2 2 0 0 0 1.808-1.144l-6.57-4.027L8 9.586l-1.239-.757Zm3.436-.586L16 11.801V4.697l-5.803 3.546Z"/>
                  </svg>
                  <span id="space"> <a href="#">maikhanhhuyen1002@gmail.com</a></span>

              </div>
              <br>
              <br>
        </div>

        <div class="col-md-7">
            <h4 id="skills"> SKILLS</h4>
            <div>
                <h5 id="space"> C/C++</h5>
                <h5 id="space"> C#</h5>
                <h5 id="space">SQL/ noSQL</h5>
                
            </div>
        </div>

        <div class="col-md-7">
            <h4 id="skills"> <a href="index.php">Home page</a></h4>
            
        </div>
    </div>

    

</div>
</div>
    </div>
</body>
</html>