


<div class="col-md-7">    
    <h2>Functions</h2>
    <div class="vmenu">
        <ul>
            <li>
                <a href="index.php">Home page</a>
            </li>
            <li>
                <a href="index.php?action=list">Players List</a>
            </li>            
            <li>
                <a href="index.php?action=add">Add Player</a>
            </li>
            <li>
                <a href="index.php?action=clubList">Clubs List</a>
            </li>
            <li>
                <a href="index.php?action=addClub">Add Club</a>
            </li>
            <li>
                <a href="18120401.phtml">18120401</a>
            </li>
        </ul>
    </div>
</div>