<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HOME</title>
    <link rel="stylesheet" type="text/css" href="css/style.css">
</head>
<body>
    <div class="header"> </div>
    <div class="banner">
        <div class="HomepageContainer">
            <p class="bannerTagLine">
                FOOLBALL
            </p>
        </div>

        <ul>
    <li><a href="index.php?action=list">Player List</a></li>
    <li>
                <a href="index.php?action=add">Add Player</a>
            </li>
            <li>
                <a href="index.php?action=clubList">Clubs List</a>
            </li>
            <li>
                <a href="18120401.phtml">18120401</a>
        </ul>
    </div>

    
</body>
</html>

