
    <table>
        <tr>
            <th>Player ID</th>
            <th>Full Name</th>
            <th>Position</th>
            <th>Number</th>
            <th>Nationality</th>
            <th>ClubName</th>
            <th> Delete Player</th>
            <th> Modify Player</th>
    
        </tr>
        <?php foreach ($data as $item): ?>
        <tr>
            <td>
                <?= $item->PlayerID ?>
            </td>
            <td>
                <?= $item->FullName ?>
            </td>
            <td>
                <?= $item->Position ?>
            </td>
            <td>
                <?= $item->Number ?>
            </td>
            <td>
                <?= $item->Nationality ?>
            </td>
            <td>
                <?= $item->ClubName ?>
            </td>
            <td>
                <a href="index.php?action=delete&PlayerID=<?= $item->PlayerID ?>">Delete</a></td>
            <td>
                <a href="index.php?action=ModifyPlayer&PlayerID">Modify</a></td>
        </tr>
        <?php endforeach; ?>
    </table>
